name: dbbe_project

services:
  siba_db_service:
    image: mariadb:latest   # OR:   mariadb:11.1.2-jammy
    container_name: siba_db_container
    env_file: .env
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./Database/SQL_Scripts/000__CreateALLdb.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    networks:
      - db_be_network

  siba_be_service:
    container_name: siba_be_container
    build: .
    env_file: .env
    depends_on:
      - siba_db_service
    environment:
      - DB_HOST=siba_db_service
    ports:
      - "${BE_SERVER_PORT}:${BE_SERVER_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - db_be_network

networks:
  db_be_network:
    driver: bridge

volumes:
  mariadb_data: